In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('fake_train.csv')


In [6]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [7]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [8]:
df.shape

(20800, 5)

In [9]:
# since this is text data, we can not able to replace the null values.
# why because we cannot replace the author with something else, we cannot replace the title with some thing else
# that's why need to drop the null values

In [10]:
df = df.dropna()

In [11]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [12]:
df.shape

(18285, 5)

In [13]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [14]:
df.describe()

id         label
count  18285.000000  18285.000000
mean   10409.807383      0.433361
std     5998.216236      0.495553
min        0.000000      0.000000
25%     5217.000000      0.000000
50%    10422.000000      0.000000
75%    15603.000000      1.000000
max    20799.000000      1.000000

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18285 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      18285 non-null  int64 
 1   title   18285 non-null  object
 2   author  18285 non-null  object
 3   text    18285 non-null  object
 4   label   18285 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 857.1+ KB


In [16]:
X = df.drop('label',axis=1)

In [17]:
X.shape

(18285, 4)

In [18]:
X.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [20]:
y= df['label']

In [21]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: label, dtype: int64

In [22]:
y.shape

(18285,)

In [23]:
y.unique()

array([1, 0])

In [24]:
import tensorflow as tf

In [25]:
tf.__version__

'2.15.0'

In [26]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [27]:
## vocabulary size
voc_size = 5000
## we may mention 10,000 as well, but if voc_size will increase
## onehot encoding representation quite big for this vocabulary

In [28]:
# one hot representation
messages=X.copy()

In [29]:
messages[0:10]

id                                              title  \
0    0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1    1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2    2                  Why the Truth Might Get You Fired   
3    3  15 Civilians Killed In Single US Airstrike Hav...   
4    4  Iranian woman jailed for fictional unpublished...   
5    5  Jackie Mason: Hollywood Would Love Trump if He...   
7    7  Benoît Hamon Wins French Socialist Party’s Pre...   
9    9  A Back-Channel Plan for Ukraine and Russia, Co...   
10  10  Obama’s Organizing for Action Partners with So...   
11  11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   

                          author  \
0                  Darrell Lucus   
1                Daniel J. Flynn   
2             Consortiumnews.com   
3                Jessica Purkiss   
4                 Howard Portnoy   
5                Daniel Nussbaum   
7                Alissa J. Rubin   
9   Megan Twohey and Scott Shane   
10                   Aaron Klein   
11               Chris Tomlinson   

                                                 text  
0   House Dem Aide: We Didn’t Even See Comey’s Let...  
1   Ever get the feeling your life circles the rou...  
2   Why the Truth Might Get You Fired October 29, ...  
3   Videos 15 Civilians Killed In Single US Airstr...  
4   Print \nAn Iranian woman has been sentenced to...  
5   In these trying times, Jackie Mason is the Voi...  
7   PARIS  —   France chose an idealistic, traditi...  
9   A week before Michael T. Flynn resigned as nat...  
10  Organizing for Action, the activist group that...  
11  The BBC produced spoof on the “Real Housewives...

In [30]:
messages.reset_index(inplace=True,drop=True)

In [31]:
messages[0:10]

id                                              title  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2   2                  Why the Truth Might Get You Fired   
3   3  15 Civilians Killed In Single US Airstrike Hav...   
4   4  Iranian woman jailed for fictional unpublished...   
5   5  Jackie Mason: Hollywood Would Love Trump if He...   
6   7  Benoît Hamon Wins French Socialist Party’s Pre...   
7   9  A Back-Channel Plan for Ukraine and Russia, Co...   
8  10  Obama’s Organizing for Action Partners with So...   
9  11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   

                         author  \
0                 Darrell Lucus   
1               Daniel J. Flynn   
2            Consortiumnews.com   
3               Jessica Purkiss   
4                Howard Portnoy   
5               Daniel Nussbaum   
6               Alissa J. Rubin   
7  Megan Twohey and Scott Shane   
8                   Aaron Klein   
9               Chris Tomlinson   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...  
5  In these trying times, Jackie Mason is the Voi...  
6  PARIS  —   France chose an idealistic, traditi...  
7  A week before Michael T. Flynn resigned as nat...  
8  Organizing for Action, the activist group that...  
9  The BBC produced spoof on the “Real Housewives...

In [32]:
messages['title'][7]

'A Back-Channel Plan for Ukraine and Russia, Courtesy of Trump Associates - The New York Times'

In [33]:
messages.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [34]:
import nltk
import re
from nltk.corpus import stopwords

In [35]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [36]:
## Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0,len(messages)):
  review = re.sub('[^a-zA-Z]',' ', messages['title'][i])
  review = review.lower()
  review = review.split()

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)


In [37]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [38]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [39]:
onehot_repr = [one_hot(words,voc_size) for words in corpus]
onehot_repr

[[2468, 3365, 4897, 2032, 1229, 2468, 1415, 3160, 3391, 1298],
 [2244, 2650, 291, 1597, 1417, 2089, 3194],
 [3650, 3539, 4814, 4574],
 [1138, 4105, 2838, 1540, 971, 3155],
 [4388, 1417, 3118, 4502, 2017, 4657, 1417, 635, 2645, 3599],
 [197,
  1005,
  1537,
  3616,
  4436,
  1359,
  479,
  3330,
  3462,
  1268,
  3150,
  1359,
  4027,
  2621,
  3194],
 [2649, 2796, 3489, 4259, 154, 22, 280, 4762, 3767, 2267, 4908],
 [1017, 1550, 2301, 2313, 3223, 1692, 1359, 424, 3767, 2267, 4908],
 [2845, 2267, 2106, 4356, 83, 3644, 1997, 1285, 1359, 2458],
 [2778, 2569, 2096, 3640, 3844, 188, 4048, 4346],
 [378, 4177, 4029, 1844, 4781, 2726, 2620, 4466, 325, 730, 4056],
 [1540, 3842, 1229, 3644, 1359, 3223],
 [4905, 4752, 1201, 285, 3882, 3096, 3442, 2007, 3330],
 [4811, 2655, 443, 3604, 3245, 380, 3131, 3767, 2267, 4908],
 [3441, 4477, 4910, 636, 4787, 3767, 2267, 4908],
 [3273, 4362, 1830, 1226, 1727, 4638, 428, 4517, 1075, 3429],
 [209, 4323, 2650],
 [1037, 1894, 4961, 2628, 1359, 1652, 747, 3194],

In [40]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [41]:
onehot_repr[1]

[2244, 2650, 291, 1597, 1417, 2089, 3194]

In [42]:
## Embedding representation

In [43]:
sent_length =30
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 3160 3391 1298]
 [   0    0    0 ... 1417 2089 3194]
 [   0    0    0 ... 3539 4814 4574]
 ...
 [   0    0    0 ... 3767 2267 4908]
 [   0    0    0 ... 1626 1312 1758]
 [   0    0    0 ... 1005 2644 1891]]


In [44]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0, 2468, 3365,
       4897, 2032, 1229, 2468, 1415, 3160, 3391, 1298], dtype=int32)

In [45]:
embedded_docs[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0, 2244, 2650,  291, 1597, 1417, 2089, 3194], dtype=int32)

In [46]:
# for tf-idf --> word embedding or word 2vec is not completly sufficent
# for LSTM --> this word embedding is sufficient

In [68]:
# creating model
from tensorflow.keras.layers import Dropout
embedding_vector_features = 50 ## 40,50,100 like hyper parameter ## 50 feature representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3)) ## it is using for reducing the over fitting
model.add(LSTM(100)) ## 100, 200 it is our choice hyperparameters
model.add(Dense(1,activation='sigmoid'))
model.compile(loss = 'binary_crossentropy',optimizer ='adam',metrics=['accuracy']) ## fake or not need to predict this is binary classification model that's
# used binary cross entory
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 30, 50)            250000    
                                                                 
 dropout (Dropout)           (None, 30, 50)            0         
                                                                 
 lstm_1 (LSTM)               (None, 100)               60400     
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 310501 (1.18 MB)
Trainable params: 310501 (1.18 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [69]:
len(embedded_docs),y.shape

(18285, (18285,))

In [70]:
y

0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 18285, dtype: int64

In [71]:
y.dtype

dtype('int64')

In [72]:
y.unique()

array([1, 0])

In [73]:
import numpy as np
X_final = np.array(embedded_docs)
y_final = np.array(y)

In [74]:
X_final.shape,y_final.shape

((18285, 30), (18285,))

In [75]:
y_final

array([1, 0, 1, ..., 0, 1, 1])

In [76]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_final,y_final,test_size=0.33,random_state=42)

In [77]:
#Model training

In [78]:
model.fit(X_train,y_train,validation_data = (X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 15s 58ms/step - loss: 0.3188 - accuracy: 0.8486 - val_loss: 0.1887 - val_accuracy: 0.9191
Epoch 2/10
192/192 [==============================] - 13s 67ms/step - loss: 0.1451 - accuracy: 0.9446 - val_loss: 0.1931 - val_accuracy: 0.9229
Epoch 3/10
192/192 [==============================] - 13s 68ms/step - loss: 0.1043 - accuracy: 0.9593 - val_loss: 0.2085 - val_accuracy: 0.9243
Epoch 4/10
192/192 [==============================] - 13s 69ms/step - loss: 0.0745 - accuracy: 0.9750 - val_loss: 0.2343 - val_accuracy: 0.9198
Epoch 5/10
192/192 [==============================] - 12s 62ms/step - loss: 0.0516 - accuracy: 0.9818 - val_loss: 0.2433 - val_accuracy: 0.9155
Epoch 6/10
192/192 [==============================] - 12s 61ms/step - loss: 0.0338 - accuracy: 0.9877 - val_loss: 0.2989 - val_accuracy: 0.9137
Epoch 7/10
192/192 [==============================] - 12s 62ms/step - loss: 0.0257 - accuracy: 0.9915 - val_loss: 0.3727 - val_accuracy:

In [79]:
### Performence MEtrics and Accuracy
y_pred = model.predict(X_test)

189/189 [==============================] - 3s 13ms/step


In [80]:
y_pred =np.where(y_pred > 0.5, 1,0) ###AUC ROC Curve

In [81]:
from sklearn.metrics import confusion_matrix

In [82]:
confusion_matrix(y_test,y_pred)

array([[3156,  263],
       [ 283, 2333]])

In [83]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9095277547638774

In [84]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92      3419
           1       0.90      0.89      0.90      2616

    accuracy                           0.91      6035
   macro avg       0.91      0.91      0.91      6035
weighted avg       0.91      0.91      0.91      6035

